### ISSUE TITLE
Change QML Widgets to QML (before GUI)

### ISSUE THREAD

**Issue by BoskiJanusz** [coders-school/desktop-business-app#36]
This task contains change Widgets but also it does need signal mechanisms in classes and QT macros to work properly. We should make few smaller tasks including:
- Widgets to QML
- cmake for QML
- extend classes for QML (inherit from QML and get Macros to work properly)
- extend mechanizm for C++ in QML
- signals for classes (setters shoult have comparison to limit processing)
- tests for signals (we can use QSignalSpy)

**Comment by Aleksiiej** [comment]
![obraz](https://github.com/coders-school/desktop-business-app/assets/94867075/ce28a1b0-20dc-4178-9af8-29f923dd4042)
Currently trying to solve problem with module "QtQuick" not installed
